[package]
name = "DBISAM-Loader"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
walkdir = "2"
csv = "1.3"
memmap2 = "0.9"
encoding_rs = "0.8.35"
dotenvy = "0.15.7"
